spring:
  application:
    name: kabal-smart-editor-api
  main:
    banner-mode: OFF
  mvc:
    throw-exception-if-no-handler-found: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  codec:
    max-in-memory-size: 32MB
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_HOST}:${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_PORT}/${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_DATABASE}
    username: ${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_USERNAME}
    password: ${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    clean-on-validation-error: false
    schemas: flyway_history_schema,klage
  sql:
    init:
      platform: postgresql
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false

server:
  port: 7095
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: false

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}


