spring:
  datasource:
    url: ${NAIS_DATABASE_KABAL_SMART_EDITOR_API_PRIV_KABAL_SMART_EDITOR_API_JDBC_URL}
    hikari:
      maximum-pool-size: 4

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
