spring:
  datasource:
    url: jdbc:postgresql://${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_HOST}:${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_PORT}/${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_DATABASE}
    username: ${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_USERNAME}
    password: ${NAIS_DATABASE_KABAL_SMART_EDITOR_API_KABAL_SMART_EDITOR_API_PASSWORD}
    hikari:
      maximum-pool-size: 4

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
